name: Publish to PyPI
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
        name: release
        url: https://pypi.org/p/xdevs
    permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
        - name: Install pypa/setuptools
          run: python -m pip install --upgrade pip build
        - name: Extract tag name
          id: tag
          run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)
        - name: Update version in setup.py
          run: >-
            sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.TAG_NAME }}/g" setup.py
        - name: Build a binary
          run: python build
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
